version: '3.1'
services:
  mongodb:
    image: mongo:4.4.0
    container_name: mongo
    environment:
        MONGO_INITDB_DATABASE: main
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    # Add remove option for volumes
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
        volume:
          nocopy: true

volumes:
  mongodb_data:
    name: mongodb_data
    driver: local
